#!/usr/bin/env python3
"""Wrap the notebook-cell Scala scripts into compilable objects.

The scripts under projection/ are Dataiku notebook CELLS: a flat
sequence of top-level statements. `scalac` cannot compile that -- Scala 2
only allows definitions at the top level of a file -- so the cells can only
be syntax-checked by pasting them into a live notebook.

This generator wraps each cell body in

    object <Name> { def run(spark: SparkSession, cfg: Map[String, String]) = { ... } }

which IS compilable, because Scala allows `import`, `def`, `val` and even
`case class` inside a method body. Compiling the result gives exactly the
compile check the notebook would give, offline and in a second.

Every CONFIG value is rewritten from a hard-coded literal into a lookup with
the original literal as the default:

    val DRY_RUN = true            ->  val DRY_RUN = cfg.getOrElse("DRY_RUN", "true").toBoolean
    val TABLE_ROOT = "hdfs://..." ->  val TABLE_ROOT = cfg.getOrElse("TABLE_ROOT", "hdfs://...")

so a test can point a cell at a temp directory without editing the script.
Defaults are preserved, so a generated wrapper run with an empty cfg behaves
exactly like the committed script.

Usage:  python generate_wrappers.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# projection/, so cells from sibling directories can be wrapped too
SRC_DIR = os.path.dirname(os.path.dirname(HERE))
OUT_DIR = os.path.join(HERE, "src", "main", "scala", "generated")

# cell file, relative to projection/ -> generated object name
CELLS = {
    "fix_runid/flatten_nested_runid_partitions.scala": "FlattenCell",
    "fix_runid/rename_partitions_to_runId.scala": "RenameCell",
    "fix_runid/recreate_table_partcol_runid.scala": "RecreateCell",
    "fix_runid/fix_all_runid_tables.scala": "FixAllCell",
    "fix_droptables/unpurge_and_drop_dbprojection.scala": "UnpurgeDropCell",
}

# `val NAME = <literal>` or `val NAME =\n  <literal>`; literal is a quoted
# string or a boolean. Anything else (derived vals such as PARTITION_KEY_LC)
# is left alone on purpose -- it must keep deriving from its source.
ASSIGN = re.compile(
    r'^(?P<indent>[ \t]*)val[ \t]+(?P<name>[A-Z][A-Z0-9_]*)'
    r'(?P<typ>[ \t]*:[ \t]*[A-Za-z\[\]]+)?[ \t]*=[ \t]*'
    r'(?P<rest>.*)$'
)
LITERAL = re.compile(r'^(?P<lit>"(?:[^"\\]|\\.)*"|true|false)[ \t]*(?P<trail>(//.*)?)$')


def parameterise(lines):
    """Turn top-level CONFIG literals into cfg lookups. Returns (lines, keys)."""
    out, keys, i = [], [], 0
    while i < len(lines):
        line = lines[i]
        m = ASSIGN.match(line)
        if not m:
            out.append(line)
            i += 1
            continue

        # the literal may sit on this line or on the next one
        rest = m.group("rest").strip()
        consumed = 1
        if rest == "" and i + 1 < len(lines):
            rest = lines[i + 1].strip()
            consumed = 2

        lm = LITERAL.match(rest)
        if not lm:
            out.append(line)
            i += 1
            continue

        name, lit, trail = m.group("name"), lm.group("lit"), lm.group("trail")
        indent = m.group("indent")
        if lit in ("true", "false"):
            expr = 'cfg.getOrElse("%s", "%s").toBoolean' % (name, lit)
        else:
            expr = 'cfg.getOrElse("%s", %s)' % (name, lit)
        out.append(("%sval %s = %s %s" % (indent, name, expr, trail)).rstrip())
        keys.append(name)
        i += consumed
    return out, keys


def wrap(cell_path, object_name, rel_name):
    body = open(cell_path, encoding="utf-8").read().split("\n")
    body, keys = parameterise(body)
    indented = "\n".join(("    " + l).rstrip() for l in body)
    header = (
        "// GENERATED by generate_wrappers.py -- DO NOT EDIT.\n"
        "// Source: projection/%s\n"
        "// Configurable keys: %s\n"
        "package generated\n\n"
        "import org.apache.spark.sql.SparkSession\n\n"
        "object %s {\n"
        "  /** The notebook cell, verbatim, with `sparkContext` bound the way\n"
        "    * Dataiku's cell 1 binds it. */\n"
        "  def run(spark: SparkSession, cfg: Map[String, String] = Map.empty): Unit = {\n"
        "    val sparkContext = spark.sparkContext\n"
        % (rel_name, ", ".join(keys), object_name)
    )
    return header + indented + "\n  }\n}\n", keys


def main():
    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)
    missing = []
    for cell, obj in sorted(CELLS.items()):
        path = os.path.join(SRC_DIR, cell)
        if not os.path.isfile(path):
            missing.append(cell)
            continue
        text, keys = wrap(path, obj, cell.replace(os.sep, "/"))
        dest = os.path.join(OUT_DIR, obj + ".scala")
        open(dest, "w", encoding="utf-8").write(text)
        print("%-52s -> %-20s (%d config keys)" % (cell, obj + ".scala", len(keys)))
    if missing:
        print("MISSING cell scripts: %s" % ", ".join(missing), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
